### ISSUE TITLE
Running tests fails on fresh install - Vite build exits

### ISSUE THREAD

**Issue by akatora28** [adonisjs/inertia#24]
### Package version

^1.1.0

### Describe the bug

Attempting to run tests via `npm run test` fails with a fresh install of Adonisjs with the Inertia starter: `npm init adonisjs@latest -- -K=inertia --adapter=react --ssr`. I've tried fresh installs with the `--no-ssr` flag and using vue and get the same issue each time.

Steps to reproduce:
1. Install with `npm init adonisjs@latest -- -K=inertia --adapter=react --ssr`
2. cd `<project-name>` ie. `inertia-latest
3. Run the test command `npm run test`

```bash
[ info ] booting application to run tests...
✘ [ERROR] The build was canceled


 NO TESTS EXECUTED 
 ~/Documents/Adonisv6/inertia-latest
```

The error seems to originate somewhere in vite, the `✘ [ERROR] The build was canceled` stems from the vite build. I've tracked down that the error is in the `runOptimizeDeps()` method in vite but haven't been able to figure out where that might be getting called in Adonis, thinking it might be in the assembler.

I added in some console logs for the Vite error:

```ts
// Line 53900 in vite chunk file
...
.catch((e) => {
console.log("53898")
console.log(e)
console.log(JSON.stringify(e.errors))
if (e.errors && e.message.includes('The build was canceled')) {
	// esbuild logs an error when cancelling, but this is expected so
	// return an empty result instead
	return cancelledResult;
}
throw e;
...
```

Output
```bash
53898
Error: Build failed with 1 error:
error: The build was canceled
    at failureErrorWithLog (inertia-latest/node_modules/esbuild/lib/main.js:1651:15)
    at inertia-latest/node_modules/esbuild/lib/main.js:1059:25
    at inertia-latest/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
[{"id":"","location":null,"notes":[],"pluginName":"","text":"The build was canceled"}]
```

**Comment by akatora28** [comment]
Well, you love to see it, I had a typo in my `.adonisrc.ts` file: 

```ts
  tests: {
    suites: [
      {
        files: ['tests/browser/**/*.spec.(.ts|.js)'],
        name: 'browser',
        timeout: 30000,
      },
  },
```
The line `files:` should've been `files: ['tests/browser/**/*.spec(.ts|.js)']` note the extra period after "spec"
