### ISSUE TITLE
Error on css extension with a module file

### ISSUE THREAD

**Issue by Mederick-ROBERT** [adonisjs/inertia#28]
### Package version

1.1.0

### Describe the bug

Hello, 

I use Adonis with inertia and react, and when I install with npm the WYSIWYG _novel_ `v.0.4.3` (with is new extension react-tweet), a new error appears : 
```
ERROR (327279): ERR_UNKNOWN_FILE_EXTENSION .css /home/me/AdonisInertiaNovel/hello-world/node_modules/react-tweet/dist/twitter-theme/tweet-header.module.css
    request_id: "hnq8ijfhk6qmuzeg3te8kg8r"
    x-request-id: "hnq8ijfhk6qmuzeg3te8kg8r"
    err: {
      "type": "Error",
      "message": "ERR_UNKNOWN_FILE_EXTENSION .css /home/me/AdonisInertiaNovel/hello-world/node_modules/react-tweet/dist/twitter-theme/tweet-header.module.css",
      "stack":
          Error: ERR_UNKNOWN_FILE_EXTENSION .css /home/me/AdonisInertiaNovel/hello-world/node_modules/react-tweet/dist/twitter-theme/tweet-header.module.css
              at defaultGetFormat (/home/me/AdonisInertiaNovel/hello-world/node_modules/ts-node/dist-raw/node-internal-modules-esm-get_format.js:93:15)
              at defer (/home/me/AdonisInertiaNovel/hello-world/node_modules/ts-node/src/esm.ts:296:7)
              at entrypointFallback (/home/me/AdonisInertiaNovel/hello-world/node_modules/ts-node/src/esm.ts:304:22)
              at getFormat (/home/me/AdonisInertiaNovel/hello-world/node_modules/ts-node/src/esm.ts:338:26)
              at /home/me/AdonisInertiaNovel/hello-world/node_modules/ts-node/src/esm.ts:245:17
              at addShortCircuitFlag (/home/me/AdonisInertiaNovel/hello-world/node_modules/ts-node/src/esm.ts:409:21)
              at load (/home/me/AdonisInertiaNovel/hello-world/node_modules/ts-node/src/esm.ts:239:12)
              at nextLoad (node:internal/modules/esm/hooks:864:28)
              at HotHookLoader.load (file:///home/me/AdonisInertiaNovel/hello-world/node_modules/hot-hook/build/src/loader.js:129:30)
              at load (file:///home/me/AdonisInertiaNovel/hello-world/node_modules/hot-hook/build/src/loader.js:179:42)
      "status": 500
    }
```

When I remove _novel_ and all its packages, and I install react-tweet alone, same error appears ...

**Comment by Julien-R44** [comment]
Probably not related to adonisjs/inertia nor with adonisjs at all, so I will close the issue. Either it's a problem with the react-tweet package, or you arere configuring it incorrectly: it seems that your .css is imported server side, through ts-node
