### ISSUE TITLE
Adonis inertia:svelte starter is broken

### ISSUE THREAD

**Issue by Blackwidow-sudo** [adonisjs/inertia#37]
### Package version

1.2.2

### Describe the bug

I just wanted to start a new adonis project using inertia with svelte, but sadly its broken out of the box.
When i run `pnpm run dev` i get the following error:
```sh
[22:25:55.904] ERROR (155414): Cannot find module '@inertiajs/core' imported from '/node_modules/.pnpm/@inertiajs+svelte@1.2.0_svelte@4.2.19/node_modules/@inertiajs/svelte/src/index.js'
    request_id: "jv9efgfuoml8gwxtr1shwzbj"
    x-request-id: "jv9efgfuoml8gwxtr1shwzbj"
    err: {
      "type": "Error",
      "message": "Cannot find module '@inertiajs/core' imported from '/node_modules/.pnpm/@inertiajs+svelte@1.2.0_svelte@4.2.19/node_modules/@inertiajs/svelte/src/index.js'",
      "stack":
          Error: Cannot find module '@inertiajs/core' imported from '/node_modules/.pnpm/@inertiajs+svelte@1.2.0_svelte@4.2.19/node_modules/@inertiajs/svelte/src/index.js'
              at fetchModule (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:54403:19)
              at ssrFetchModule (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:54455:10)
              at Object.ssrFetchModule [as fetchModule] (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:62806:14)
              at ViteRuntime.cachedModule (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/runtime.js:953:110)
              at request (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/runtime.js:963:40)
              at eval (/home/user/js/wishman/node_modules/.pnpm/@inertiajs+svelte@1.2.0_svelte@4.2.19/node_modules/@inertiajs/svelte/src/index.js:3:50)
              at ESModulesRunner.runViteModule (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/runtime.js:1045:6)
              at ViteRuntime.directRequest (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/runtime.js:1018:78)
              at ViteRuntime.cachedRequest (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/runtime.js:937:28)
              at request (file:///home/user/js/wishman/node_modules/.pnpm/vite@5.4.8_@types+node@20.16.10/node_modules/vite/dist/node/runtime.js:964:128)
      "code": "ERR_MODULE_NOT_FOUND",
      "status": 500
    }
```
At first i thought maybe its a peer-dependency issue, so i added a `.npmrc` with `auto-install-peers=true` to re-install with `pnpm i`, but that did nothing.
I started with the following configuration using `pnpm create adonisjs@latest my-project`
```sh
❯ Which starter kit would you like to use · Inertia Starter Kit
❯ Which authentication guard you want to use · session
❯ Which database driver you want to use · sqlite
❯ Which frontend adapter you want to use with Inertia · svelte
❯ Do you want to setup server-side rendering with Inertia (y/N) · true
❯ Download starter kit (461 ms)
  Downloaded "github:adonisjs/inertia-starter-kit"
❯ Install packages (8.1 s)
  Packages installed using "pnpm"
❯ Prepare application (575 ms)
  Application ready
❯ Configure Lucid (7.18 s)
  Lucid configured to use "sqlite" database
❯ Configure Auth (2.5 s)
  Auth configured to use "session" guard
❯ Configure Inertia (8.98 s)
  Inertia configured
```
I wasn't sure if i should create the issue here or in adonis/core (or maybe its a problem of the intertia svelte adapter). Please forgive me if this is the wrong place. I didn't have the time to look deeper into it.

Node is v22.9.0 and `pnpm ls`:
```sh
dependencies:
@adonisjs/auth 9.2.3     @adonisjs/cors 2.2.1     @adonisjs/lucid 21.2.0   @adonisjs/shield 8.1.1   @adonisjs/vite 3.0.0     @vinejs/vine 2.1.0       edge.js 6.2.0            reflect-metadata 0.2.2   
@adonisjs/core 6.14.0    @adonisjs/inertia 1.2.2  @adonisjs/session 7.5.0  @adonisjs/static 1.1.1   @inertiajs/svelte 1.2.0  better-sqlite3 11.3.0    luxon 3.5.0              svelte 4.2.19            

devDependencies:
@adonisjs/assembler 7.8.2           @japa/assert 3.0.0                  @swc/core 1.7.26                    hot-hook 0.3.0                      typescript 5.6.2                    
@adonisjs/eslint-config 1.3.0       @japa/plugin-adonisjs 3.0.1         @types/luxon 3.4.2                  pino-pretty 11.2.2                  vite 5.4.8                          
@adonisjs/prettier-config 1.4.0     @japa/runner 3.1.4                  @types/node 20.16.10                prettier 3.3.3                      
@adonisjs/tsconfig 1.4.0            @sveltejs/vite-plugin-svelte 3.1.2  eslint 8.57.1                       ts-node-maintained 10.9.4 
```

EDIT:
I just ran `pnpm create adonisjs@latest` again, but this time without SSR:
```
❯ Do you want to setup server-side rendering with Inertia (y/N) · false
```
Works fine with that. So there seems to be an issue with the SSR setup.

**Comment by Julien-R44** [comment]
Seems to be an issue with pnpm rather than Adonis. If you install your packages with `npm`, or keep `pnpm` but add a `shamefully-hoist=true` in your `.npmrc`, I think it will work

If that's the case, then I don't think there's anything we can do

**Comment by Blackwidow-sudo** [comment]
> Seems to be an issue with pnpm rather than Adonis. If you install your packages with `npm`, or keep `pnpm` but add a `shamefully-hoist=true` in your `.npmrc`, I think it will work
> 
> If that's the case, then I don't think there's anything we can do

Im sorry, should've tried that first. Thank you ❤
